In [1]:
print("Hello World!")

Hello World!


In [2]:
a =1

In [3]:
a

1

In [4]:
b = [1,2,3,4,5]

In [7]:
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [9]:
import random
import time

try:
    with open("word.txt", 'r') as f:
        word = f.read().split()  # word.txt 파일의 단어들을 리스트로 저장

    input("타자 게임 준비되면 엔터!!")
    start = time.time()  # 시작 시간 기록

    n = 1  # 문제 번호
    while n < 11:  # 10문제 출제
        print("문제", n)
        question = random.choice(word)  # 랜덤하게 단어 선택
        print(question)  # 문제 출제
        user = input()  # 사용자 입력
        
        if question == user:  # 정답이면
            print("통과!!")
            n += 1
        else:  # 오답이면
            print("오타!! 다시 도전")
        
        end = time.time()
        print(f"게임 소요 시간 : {end-start:.2f}초")

except:
    print("파일을 찾을 수 없습니다.")


문제 1
earth
오타!! 다시 도전
게임 소요 시간 : 1.04초
문제 1
tree
통과!!
게임 소요 시간 : 3.77초
문제 2
moon
통과!!
게임 소요 시간 : 5.97초
문제 3
strawberry
통과!!
게임 소요 시간 : 11.45초
문제 4
sky
통과!!
게임 소요 시간 : 13.80초
문제 5
flower
통과!!
게임 소요 시간 : 16.17초
문제 6
garlic
통과!!
게임 소요 시간 : 21.52초
문제 7
onion
통과!!
게임 소요 시간 : 25.78초
문제 8
moon
오타!! 다시 도전
게임 소요 시간 : 27.51초
문제 8
potato
오타!! 다시 도전
게임 소요 시간 : 30.55초
문제 8
flower
통과!!
게임 소요 시간 : 33.53초
문제 9
flower
통과!!
게임 소요 시간 : 34.98초
문제 10
flower
통과!!
게임 소요 시간 : 36.26초


In [7]:
import numpy as np
x = np.array([3,1,2])
print(x)
print(type[x])
print(type([3,1,2]))


[3 1 2]
type[array([3, 1, 2])]
<class 'list'>


In [5]:
c= [[1],[1,2]]
d = np.array([[1,1],[1,2]])

for x,y in d:
    print(x,y)

1 1
1 2


In [8]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 7291-91F2

 c:\Users\zer12\Desktop\git-test ���͸�

2024-12-13  ���� 11:44    <DIR>          .
2024-12-13  ���� 11:44    <DIR>          ..
2024-12-11  ���� 12:49    <DIR>          __pycache__
2024-11-30  ���� 10:08               722 1.py
2024-12-02  ���� 08:54             3,122 2.py
2024-12-03  ���� 01:53             3,524 241203.py
2024-12-05  ���� 01:13             3,348 241204.py
2024-12-06  ���� 09:17            11,110 241205.py
2024-12-06  ���� 01:53             3,538 241206.py
2024-12-07  ���� 01:49             3,534 241207.py
2024-12-09  ���� 01:53             7,121 241209.py
2024-12-10  ���� 11:15             5,067 241210.py
2024-12-12  ���� 10:39             2,546 241211.py
2024-12-13  ���� 09:13            11,648 241212.py
2024-12-13  ���� 11:44             3,356 241213.py
2024-12-03  ���� 09:20             4,559 3.py
2024-11-29  ���� 10:47                15 3ea.txt
2024-12-11  ���� 12:53    <DIR>          bbb
2024-12-10  ����

In [9]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [14]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y / 2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [15]:
print(x.ndim)

1


In [17]:
a = np.array([[1,2], [3,4], [5,6]])
print(a.ndim)

2


In [18]:
print(a.shape)

(3, 2)


In [21]:
a = np.array([[[1],[2]], [[3],[4]], [[5],[6]]])
print(a.ndim)

3


In [22]:
print(a.shape)

(3, 2, 1)


In [23]:
a = np.array([[[1,2],[2,2]], [[3,2],[4,2]], [[5,2],[6,2]]])

In [24]:
print(a.ndim)
print(a.shape)

3
(3, 2, 2)


In [25]:
np.dot(4,2)

8

In [27]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)


24

In [28]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)


array([[ 7, 10],
       [15, 22]])

In [29]:
ndar1 = np.array([[1,2],[4,5]])
ndar1 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2) # (a,b) * (b,c) b위치 같아야함.

array([[ 7, 10],
       [15, 22]])

In [32]:
ndar2 = np.array([[6,3],[5,2],[4,1]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)


(3, 2)
2
1
[[6 3]
 [5 2]
 [4 1]]


In [33]:
ndarr = np.array([[1,2],[2,3],[3,4]]) # 3X2
ndarr.reshape(2,3) # 배열의 차원을 변경

array([[1, 2, 2],
       [3, 3, 4]])

In [35]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [36]:
np.random.randint(5, size=(2,4))

array([[1, 1, 4, 0],
       [4, 2, 4, 3]])

In [38]:
np.random.rand(2,4)

array([[0.05243432, 0.71805665, 0.42987965, 0.51586311],
       [0.99581104, 0.0716856 , 0.15270293, 0.97349581]])

In [40]:
rng = np.random.default_rng()


In [41]:
rng.random()

0.9115386346920135

In [42]:
rng.integers(0, 10, (2,4) )

array([[0, 1, 1, 1],
       [2, 3, 8, 0]], dtype=int64)

In [43]:
ndarr = np.array([[6,3],[5,2],[4,1]])

In [44]:
ndarr > 4


array([[ True, False],
       [ True, False],
       [False, False]])

In [45]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr[ndarr > 4]

array([6, 5])