In [9]:
print("Hello World!")

Hello World!


In [10]:
a =1

In [11]:
a

1

In [12]:
b = [1,2,3,4,5]

In [13]:
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
import random
import time

try:
    with open("word.txt", 'r') as f:
        word = f.read().split()  # word.txt 파일의 단어들을 리스트로 저장

    input("타자 게임 준비되면 엔터!!")
    start = time.time()  # 시작 시간 기록

    n = 1  # 문제 번호
    while n < 11:  # 10문제 출제
        print("문제", n)
        question = random.choice(word)  # 랜덤하게 단어 선택
        print(question)  # 문제 출제
        user = input()  # 사용자 입력
        
        if question == user:  # 정답이면
            print("통과!!")
            n += 1
        else:  # 오답이면
            print("오타!! 다시 도전")
        
        end = time.time()
        print(f"게임 소요 시간 : {end-start:.2f}초")

except:
    print("파일을 찾을 수 없습니다.")


문제 1
flower
오타!! 다시 도전
게임 소요 시간 : 0.50초
문제 1
grape
오타!! 다시 도전
게임 소요 시간 : 3.07초
문제 1
tree
오타!! 다시 도전
게임 소요 시간 : 152.31초
문제 1
onion


In [7]:
import numpy as np
x = np.array([3,1,2])
print(x)
print(type[x])
print(type([3,1,2]))


[3 1 2]
type[array([3, 1, 2])]
<class 'list'>


In [5]:
c= [[1],[1,2]]
d = np.array([[1,1],[1,2]])

for x,y in d:
    print(x,y)

1 1
1 2


In [8]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 7291-91F2

 c:\Users\zer12\Desktop\git-test ���͸�

2024-12-13  ���� 11:44    <DIR>          .
2024-12-13  ���� 11:44    <DIR>          ..
2024-12-11  ���� 12:49    <DIR>          __pycache__
2024-11-30  ���� 10:08               722 1.py
2024-12-02  ���� 08:54             3,122 2.py
2024-12-03  ���� 01:53             3,524 241203.py
2024-12-05  ���� 01:13             3,348 241204.py
2024-12-06  ���� 09:17            11,110 241205.py
2024-12-06  ���� 01:53             3,538 241206.py
2024-12-07  ���� 01:49             3,534 241207.py
2024-12-09  ���� 01:53             7,121 241209.py
2024-12-10  ���� 11:15             5,067 241210.py
2024-12-12  ���� 10:39             2,546 241211.py
2024-12-13  ���� 09:13            11,648 241212.py
2024-12-13  ���� 11:44             3,356 241213.py
2024-12-03  ���� 09:20             4,559 3.py
2024-11-29  ���� 10:47                15 3ea.txt
2024-12-11  ���� 12:53    <DIR>          bbb
2024-12-10  ����

In [9]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [14]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y / 2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [15]:
print(x.ndim)

1


In [17]:
a = np.array([[1,2], [3,4], [5,6]])
print(a.ndim)

2


In [18]:
print(a.shape)

(3, 2)


In [21]:
a = np.array([[[1],[2]], [[3],[4]], [[5],[6]]])
print(a.ndim)

3


In [22]:
print(a.shape)

(3, 2, 1)


In [23]:
a = np.array([[[1,2],[2,2]], [[3,2],[4,2]], [[5,2],[6,2]]])

In [24]:
print(a.ndim)
print(a.shape)

3
(3, 2, 2)


In [25]:
np.dot(4,2)

8

In [27]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)


24

In [28]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)


array([[ 7, 10],
       [15, 22]])

In [29]:
ndar1 = np.array([[1,2],[4,5]])
ndar1 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2) # (a,b) * (b,c) b위치 같아야함.

array([[ 7, 10],
       [15, 22]])

In [32]:
ndar2 = np.array([[6,3],[5,2],[4,1]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)


(3, 2)
2
1
[[6 3]
 [5 2]
 [4 1]]


In [33]:
ndarr = np.array([[1,2],[2,3],[3,4]]) # 3X2
ndarr.reshape(2,3) # 배열의 차원을 변경

array([[1, 2, 2],
       [3, 3, 4]])

In [35]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [36]:
np.random.randint(5, size=(2,4))

array([[1, 1, 4, 0],
       [4, 2, 4, 3]])

In [38]:
np.random.rand(2,4)

array([[0.05243432, 0.71805665, 0.42987965, 0.51586311],
       [0.99581104, 0.0716856 , 0.15270293, 0.97349581]])

In [40]:
rng = np.random.default_rng()


In [41]:
rng.random()

0.9115386346920135

In [42]:
rng.integers(0, 10, (2,4) )

array([[0, 1, 1, 1],
       [2, 3, 8, 0]], dtype=int64)

In [43]:
ndarr = np.array([[6,3],[5,2],[4,1]])

In [46]:
ndarr > 3


array([[ True, False],
       [ True, False],
       [ True, False]])

In [49]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr[ndarr > 3]

array([6, 5, 4])

In [50]:
ndarr[1:]

array([[5, 2],
       [4, 1]])

In [ ]:
np.zeros(2,2)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [26]:
#실습. numpy 모듈 사용해보기1
import numpy as np
# 10개의 0으로 채워진 array를 만들고 출력
# arr1 = np.zeros(10)
# print(arr1)
# 1번에서 만들어진 array에서 5번째 값을 1로 바꾸고 출력
# arr1[4] = 1
# print(arr1)
# 10부터 30까지의 수로 이루어진 array 만들고 출력
# arr2 = np.arange(10,31)
# print(arr2)
# 0부터 99까지의 난수로 이루어진 2x2 array를 만들고 출력
# arr3 = np.random.randint(0, 100, (2,2))
# print(arr3)
# 0부터 1사이의 난수로 이루어진 2x4 array를 만들고 출력
# arr4 = np.random.rand(2,4)
# print(arr4)
# 6.35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x4 행렬로 변환 후 출력
arr5 = np.arange(35,75)
print(arr5)
arr5_1 = arr5.reshape(10,4)
print(arr5_1)
# 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력
arr6 = arr5_1[::-1]
print(arr6)
# 6번에서 만든 배열 중 두 번쨰 행부터 마지막 진전 행까지, 세번째 열부터 마지막 열까지 슬라이싱해서 출력
arr7 = arr5_1[1:-1, 2:]
print(arr7)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [38]:
import numpy as np
# 9 6번에서 만든 배열에서 마지막 열에 해당되는 모든 값을 출력 (1차원 배열로)
arr5 = np.arange(35,75).reshape(10,4)
arr9 = arr5[:, -1]
print(arr9)
# 9-1 6번에서 만든 배열에서 마지막 열에 해당되는 모든 값을 출력 (2차원 배열로)
arr9_1 = arr9.reshape(10,1)
print(arr9_1)
# 10 9-1번에서 만든 배열을 역순으로 정렬해서 출력
arr10 = arr9_1[::-1]
print(arr10)
# 11. 1부터 50까지의 난수로 된 5x6 배열로 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성
arr11 = np.random.randint(1, 51, (5,6))
print(arr11)
even11 = arr11[arr11 % 2 == 0]
print(even11)
# 11번 rng 버전
rng = np.random.default_rng()
ndarr = rng.integers(1,51, size=(5,6))
print(ndarr)
print(ndarr[ndarr%2 == 0])

[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[44 24 29 19 15 27]
 [12 50 25 28 50 39]
 [37 11 31  6  4 11]
 [ 7 15 35  3 29  3]
 [18 34 31 16 19 11]]
[44 24 12 50 28 50  6  4 18 34 16]
[[26 15 22 47 33 17]
 [27 25 31 48 11 17]
 [46 12 24 45 37 32]
 [44  4 37  9 12 25]
 [30  4 32 11 12 24]]
[26 22 48 46 12 24 32 44  4 12 30  4 32 12 24]


In [41]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a.shape)

expanded = np.expand_dims(a,0)
print(expanded)
print(expanded.shape)

expanded = np.expand_dims(a,1)
print(expanded)
print(expanded.shape)

expanded = np.expand_dims(a,2)
print(expanded)
print(expanded.shape)


(2, 2)
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [43]:
np_ones = np.ones((1,2,1,3))
print(np_ones)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]] # 노란색안에 보라색1개, 보라색안에 파란색2개, 파란색안에 노란색1개, 노란색안에 1이 3개

squeezed = np.squeeze(np_ones) #1,2,1,3 > 1만 삭제: 2,3
print(squeezed)
print(squeezed.shape)

squeezed = np.squeeze(np_ones, 0) #1,2,1,3 > 0번째 위치 지우기
print(squeezed)
print(squeezed.shape)

squeezed = np.squeeze(np_ones, 2) # 1,2,1,,3 > 2번째 위치 지우기
print(squeezed)
print(squeezed.shape)



[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)


In [45]:
a = [1,2,2,3,4,3,4,3,1]
u_a, counts = np.unique(a,return_counts=True)
print(u_a)
print(counts)

[1 2 3 4]
[1 2 3 2]


In [47]:
a = [1,2,2,3,4,3,4,3,1]
u_a, indexs = np.unique(a,return_index=True)
print(u_a)
print(indexs)

[1 2 3 4]
[0 1 3 4]


In [50]:
a = [1,2,2,3,4,3,4,3,1]
u_a, indexs, counts = np.unique(a,return_index=True, return_counts=True) #인덱스 > 카운츠 순서
print(u_a)
print(indexs)
print(counts)

[1 2 3 4]
[0 1 3 4]
[2 2 3 2]


In [53]:
def add(a=1, b=1):
    return a,b,a+b #리턴순서에 따른 결과

a,b,sum = add(2,3) 
print(a,b,sum) 

sum,a,b = add(2,3) #sum=2, a=3, b=5 
print(a,b,sum) # 3,5,2

def add(a=1, b=1):
    return a,b,a+b #리턴순서에 따른 결과
sum,a,b = add(b=2,a=3) #sum=3 a=2 b=5
print(a,b,sum) #2,5,3

2 3 5
3 5 2
2 5 3


In [54]:
a = np.array([1,4,2,3])
b = np.sort(a)
print(f"a {a}") # 1,4,2,3
print(f"b {b}") # 1,4,2,3 를 정렬해서 1,2,3,4
c = np.argsort(a) # 원본 행렬이 정렬 되었을때 해당 원소의 인덱스 반환
print(f"c {c}") # 1 4 2 3 원본 행렬
                # 1 2 3 4 원본 정렬
                # 0 1 2 3 위치  
                # 0 2 3 1 위치 변환
print(f"cc {a[c]}") # 1 2 3 4 c의 0 2 3 1 > a의 0번째가 1 a의 2번째가 2 a의 3번째가 3 a의 1번째가 4
a.sort()
print(f"a {a}")




a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]


In [55]:
a = np.array([1,2,3,4])
np.mean(a)

2.5

In [56]:
np.std(a)

1.118033988749895

In [57]:
np.var(a)

1.25

In [58]:
np.max(a)

4

In [59]:
np.min(a)

1

In [60]:
np.sum(a)

10

In [62]:
np.prod(a)

24

In [63]:
np.median(a)

2.5

In [70]:
a = np.array([1,2,3,4,5,100])
np.median(a)


3.5

In [69]:
a = np.array([1,2,3,4,5,100,1000])
np.median(a)

4.0

In [82]:
#실습.Numpy 모듈 사용해보기2

a = ([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
# 1.중복을 제거한 배열 출력
unique_a = np.unique(a)
print(unique_a)
# 2. 1의 결과의 최대,최소,평균값을 출력
print(np.max(unique_a))
print(np.min(unique_a))
print(np.mean(unique_a))
# 3. 1의 결과의 모든 합 출력
print(np.sum(unique_a))
# 4. 중복을 제거하지 않은 배열의 중간값 출력
not_unique_a = np.array(a)
#print(not_unique_a)
print(np.median(not_unique_a))

[  1   2   3   4   5   7   8   9  10  11  24 100]
100
1
15.333333333333334
184
5.0


In [110]:
#실습. Numpy 모듈 사용해보기3
x = np.arange(15, dtype=np.int64).reshape(3, 5)
#print(x)
x[1:, ::2] = -99 #1행부터 끝까지, 2칸 간격으로(0번째,2번째,4번째 열) 변환
print(x)
# 1. 1열의 최대,최소,평균값 출력
print(np.max(x[:,0])) #1열
print(np.min(x[:,0])) #1열
print(np.mean(x[:,0])) #1열
# 2. 2행의 모든 합출력
print(np.sum(x[1,:])) #2행 
# 3. 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬
a = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
b = np.argsort(a)[::-1] #np.argsort
print(a[b])

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
0
-99
-66.0
-283
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
